version: '3.8'

services:
  api:
    image: meu-usuario/mcp_api:1.0   # sua imagem já publicada ou importada
    container_name: mcp_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app               # opcional: monta código para hot-reload
      - mcp_data:/app/mcp.db  # persiste o SQLite
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.mcp_api.rule=Host(`mcpfinanceiro.adjunto.com.br`)"
      - "traefik.http.routers.mcp_api.entrypoints=websecure"
      - "traefik.http.routers.mcp_api.priority=1"
      - "traefik.http.routers.mcp_api.tls.certresolver=le"
      - "traefik.http.routers.mcp_api.middlewares=mcp_api-security"
      - "traefik.http.middlewares.mcp_api-security.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.mcp_api-security.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.mcp_api-security.headers.stsPreload=true"
      - "traefik.http.middlewares.mcp_api-security.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.mcp_api-security.headers.browserXssFilter=true"
      - "traefik.http.middlewares.mcp_api-security.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.mcp_api-security.headers.frameDeny=true"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.5'
    networks:
      - traefik_public
      - agent_network

volumes:
  mcp_data:
    driver: local

networks:
  traefik_public:
    external: true
  agent_network:
    external: true
