"""Inclusoes de outros campos adicionais como celular, endereço, tipo, status

Revision ID: 9a6b409b0fec
Revises: 9cac4c2517dc
Create Date: 2025-06-19 11:14:17.152386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6b409b0fec'
down_revision: Union[str, Sequence[str], None] = '9cac4c2517dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
