"""Inclusoes de outros campos adicionais como celular, endereço, tipo, status

Revision ID: 9cac4c2517dc
Revises: 615e4739a88b
Create Date: 2025-06-19 11:13:51.476005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cac4c2517dc'
down_revision: Union[str, Sequence[str], None] = '615e4739a88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
